### ISSUE TITLE
Deployment fails due to permission issues

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/honeybee-core#4]
@AntoineDao  FYI: https://travis-ci.org/ladybug-tools/honeybee-core/jobs/540818555#L616

Not sure why this is happening as the set-up here is almost identical to set up for other libraries. It happens when it tries to execute deploy.sh.

I checked file permissions and it looks right to me. I can also run the script locally.

**Comment by mostaphaRoudsari** [comment]
fixed via https://github.com/ladybug-tools/honeybee-core/commit/4ad8493d657c87af76e22c3a208f49a93f1bf080

It looks like having `bash` before the bash file is required and travis can't figure it out from the header.

**Comment by AntoineDao** [comment]
Silly travis...
