### ISSUE TITLE
Bug in tuple_with_length

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/honeybee-core#418]
Hi @chriswmackey,

I believe we need better type checking [here](https://github.com/ladybug-tools/honeybee-core/blob/master/honeybee/typing.py#L145)

```
a = (255.12, 255, 255)
b = tuple_with_length(a, length=3, item_type=int)
print(b)
```
The above will print
`(255, 255, 255)`

Here, I would expect an error to be thrown.

I am happy to send a PR if you agree that this needs to be fixed.

**Comment by chriswmackey** [comment]
Hey @devngc ,

This is not a bug but is the intended behavior and all of the typing functions do type casting like this. There are a lot of places where we rely on this type casing to convert from string to float, for example. So I don't agree with changing this function. If you really need an assert statement to make sure an input is of a particular data type, you should add it in whatever place you need such strict type checking .
