### ISSUE TITLE
Duplication of HB rooms::Via some DF esque features?

### ISSUE THREAD

**Issue by TfedUD** [ladybug-tools/honeybee-core#488]
Hi Chris:  This is a follow up from an email chain,
If these features are "thumbs upped" I can totally add them myself, 
In the model you saw in the video: I had daisy chained the move HB obj components, in leu of using a "multiplied vector value list"
to duplicate a floor a number of times.  I had also added a "suffix" _input to the HB Move to facilitate using a company determined naming convention.

Would either adding a feature to the existing HB move compo to facilitate DF esque 'floor to floor' rather that '10,20,30' lists of vector values to 'array' HB rooms be acceptable? and or creating a new component entirely to kind of 'blend' things together as to have a multiplier in which also 'duplicates' rooms for repeated floorplans/zoning data etc?

as well as: Can I add 
```python
@property
def suffix(self)
```
to the HB_Core room obj and related functions?
![image](https://user-images.githubusercontent.com/63176386/135724270-28fbfd20-6d9b-4073-8ef4-1b52afbcdacb.png)

**Comment by TfedUD** [comment]
I suppose this actually is the singular encompassment of the aforementioned for sake of i.e lol:
![image](https://user-images.githubusercontent.com/63176386/135770641-7a5ee316-693c-45b4-976c-db03182b4769.png)

but at the same time: it feels like a nit-picky thing; and more so a "I have an idea", rather than an "I have a productive enhancement idea", as works just the same as is when applies some Gh common core to. hmmm

**Comment by chriswmackey** [comment]
Hey @TfedUD ,

Sorry that I missed seeing this a long time ago. I'm having a little trouble figuring out what the final takeaway/feature request is here. Is it just that you'd like to have `add_suffix` methods implemented across honeybee-core?

**Comment by TfedUD** [comment]
@chriswmackey no worries!!! I honestly forgot about this and I don't even really remember what the thing about it was soooo can prolly just close this 😅 and if whatever it is comes up again; is something I can send a PR for if I ever remember what the thing was 🤣
