### ISSUE TITLE
Consider changing the AirWall face type to be called AirBoundary instead

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-core#58]
I know that @mostaphaRoudsari brought up earlier that the word "Wall"  in "AirWall" might be misleading because it can be used for all types of Faces (including ceilings + floors). At the time that Mostapha brought this up, "AirWall" seemed to be the clearest name that I could think of since just "Air" on its own was a bit too vague to identify it as a face type and the name that I know Design Builder uses for these surfaces (VirtualPartition) isn't really standard industry nomenclature.

But I just realized that EnergyPlus seems to be using the name "AirBoundary":
https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-surface-construction-elements.html#constructionairboundary

The more that I think about it, "AirBoundary" might be clearer than "AirWall". If we are going to change it, we should do it now before I build out any more of this functionality. and it becomes harder to change. @mostaphaRoudsari , what do you think?

**Comment by mostaphaRoudsari** [comment]
Good find! I like the new name much better.

**Comment by chriswmackey** [comment]
👍  I'll start implementing it, then.

**Comment by chriswmackey** [comment]
This has been addressed.
